### ISSUE TITLE
What

### ISSUE THREAD

**Issue by TheOfficialNano** [YSelfTool/MapRend#1]
Very nice... but how do i use it? i've downloaded the files... where do i start the program?

**Comment by YSelfTool** [comment]
<s>You first need to build the program to start it.</s>
I've just added a prebuilt MapRend.jar to the repository. It's built with Java 8. 

To run the program, you need to open a terminal ([Windows](http://www.sevenforums.com/tutorials/27778-open-command-window-here.html), <sub>if you use Linux you probably know how to open a terminal</sub>) in the folder where you've downloaded the files. To run the program type
`java -jar MapRend.jar`
and press Return. 
It will then show you the help.
First you need to generate a `colors.json`. For that you get the ressource pack of your choice, create the subfolder `ressource` and `ressource/raw` in your folder (where you've downloaded the files) and copy all files from `assets/minecraft/textures/blocks/` from the ressource pack the `ressource/raw`. Then run
`java -jar MapRend.jar textures ressource`.
Now you can generate the map of your world. For that you need the world you want to map. Copy the world (the whole folder from `.minecraft/saves/`) to your folder (where you've downloaded the files (I'll just call that one the working folder from now on)). 
In my case I created a folder `tmp/` in my working folder and copied the world to `tmp/New World`.
To generate the map run
`java -jar MapRend.jar map "tmp/New World" ressource`.
Of course you need to replace tmp/New World by the path to your world. The "" are needed, because in this case the world name (New World) contains a whitespace. 
The map image has been generated to the folder where your world is (in my case `tmp/New World-day.png`).

How to improve the above process:
- You do not need to copy the world. You can just reference it where it is. Instead of the tmp/New World above, just use the path to your world in the minecraft saves folder (on Linux it's usually `~/.minecraft/saves/New World`, on Windows something like `C:\Users\Username\AppData\roaming\.minecraft\saves\New World`).
- You can specify the folder, where the map is saved. To put it in the working folder, run
  `java -jar MapRend.jar map "tmp/New World" ressource .`.
  To put it in your Pictures directory, run
  `java -jar MapRend.jar map "tmp/New World" ressource "C:\Users\Username\Pictures\"` or similar.
- You can get a night map. Run
  `java -jar MapRend.jar map "tmp/New World" ressource . night`.
- To set the radius of the mapped area to e.g. 500, run 
  `java -jar MapRend.jar map "tmp/New World" ressource . day 500`.
- If you want a rectangular map of the world instead, run
  `java -jar MapRend.jar map "tmp/New World" ressource . day 500 rect`.

There are some more options. Be aware that only the options at the far end are optional, not the ones inbetween. (`java -jar MapRend.jar map "tmp/New World" ressource . day` works, `java -jar MapRend.jar map "tmp/New World" ressource . rect` not.)

If there are still questions (usually there are), feel free to ask.

**Comment by TheOfficialNano** [comment]
So i've been messing around with the inputs and im beginning to be certain that i am not doing something wrong here 
http://oi62.tinypic.com/6hqka8.jpg

**Comment by YSelfTool** [comment]
The problem should be, that I compiled the program with version 8 of java (to be exact: With openjdk). Previous versions of java, although compatible, can't run it.
EDIT: I've now compiled the program with Java 7. As long as you have that version installed, it should now run (of course you need to pull the repository/redownload the files).
To find out your [installed Java version](https://www.java.com/de/download/help/version_manual.xml).

**Comment by TheOfficialNano** [comment]
i am aware, but i did install java 8 to try again, but still got the same error....
What on earth is openjdk?

**Comment by YSelfTool** [comment]
OpenJDK is a free implementation of Java.
I forgot to clear the cache, so the last version was not really compiled with Java 7.
Now it runs fine even with Java 6 here.
Could you try running it again?

**Comment by TheOfficialNano** [comment]
It cant find colors.json.... nor can i tho.

**Comment by YSelfTool** [comment]
You need to generate that `colors.json` (sorry, above I wrote `textures.json`, that was wrong) by copying the files from `assets/minecraft/textures/blocks/` into the folder `ressource/raw` and running 
`java -jar MapRend.jar textures ressource`.

**Comment by TheOfficialNano** [comment]
correction, it says Cannot open colors.json

**Comment by TheOfficialNano** [comment]
Sorry i cant respond any longer g2g

**Comment by YSelfTool** [comment]
Do you run
`java -jar MapRend.jar map tmp/world ressource`
or just
`java -jar MapRend.jar map tmp/world`?
The first one is correct, the second one assumes the working folder (called `.`), not the ressource folder inside the working folder (called `./ressource`) is the ressource folder.

**Comment by TheOfficialNano** [comment]
I do run the first one. it says
"Cannot find stone texture"

**Comment by YSelfTool** [comment]
Which ressource pack do you use?
Some ressource packs don't replace every texture (usually then the default texture is used) and therefor textures are missing for the mapper.

**Comment by TheOfficialNano** [comment]
i dont use any texturepacks.

**Comment by YSelfTool** [comment]
Not for minecraft, but for creating the map.
MapRend needs a ressource pack to get the color of the blocks. 

> First you need to generate a colors.json. For that you get the ressource pack of your choice, create the subfolder ressource and ressource/raw in your folder (where you've downloaded the files) and copy all files from assets/minecraft/textures/blocks/ from the ressource pack the ressource/raw. 

If you want to use the default Minecraft textures, you need to extract them from the minecraft.jar-file.
It's (for Windows) in `C:\Users\Username\AppData\roaming\.minecraft\versions\1.8.1\minecraft.jar`. 
Open it with 7zip or similar programs and copy all files from `assets/minecraft/textures/blocks/` to `ressource/raw/` in your working folder.

**Comment by TheOfficialNano** [comment]
Alright! that all works now :) but now i cant find biomes.json

**Comment by YSelfTool** [comment]
You need to copy `biomes.json` from your working folder to `ressource/`, then it should work.
Seems like I should streamline some parts of how to use this program.

**Comment by TheOfficialNano** [comment]
YES NOW IT SEEMS TO MAKE PROGRESS :D
AND YET ANOTHER PROBLEM
"stopping: Unable to load and draw chunk!"

**Comment by TheOfficialNano** [comment]
i think its bitching about the height limit being at 255

**Comment by YSelfTool** [comment]
What does it say before stopping: ...? There should be some stacktrace. Could you send a screenshot of that stacktrace?

**Comment by TheOfficialNano** [comment]
http://oi59.tinypic.com/281ag4z.jpg

**Comment by YSelfTool** [comment]
Seems like there are new biomes.

**Comment by TheOfficialNano** [comment]
the world is in 1.7.2

**Comment by YSelfTool** [comment]
Correction: The program thinks there should be a biome with ID 255. The biome id is saved per chunk in the world file.

**Comment by YSelfTool** [comment]
Could you try it with another world and/or send me the world it's not working for?

**Comment by TheOfficialNano** [comment]
I made a new flatworld.. gonna try it with that

**Comment by TheOfficialNano** [comment]
Sweet mother of god, its working
http://oi59.tinypic.com/30xbm8y.jpg

**Comment by YSelfTool** [comment]
I've patched the program, so even for invalid biomes it should now work (by using the color of grass in plains).

**Comment by YSelfTool** [comment]
And congratulations for getting it to work :)

**Comment by TheOfficialNano** [comment]
aaah :+1:

**Comment by jamonholmgren** [comment]
For Mac OSX, I've added installation and usage instructions (#2) to the README.md in a pull request.
